henshin:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: 'henshin.db'
      schema_directory: '/Users/5p4rk3r/Projects/Python/Data Artisans/Analytics Engineer/Data Engineer/DBT/Henshin/henshin.db'
      #optional fields
      extensions:
        - "/path/to/sqlean/crypto.so"